fix: pre-commit

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,1 +1,12 @@
-npm test
+echo "🎯💈 Formatting and linting staged files with Biome before committing 💈🎯"
+echo "Please be patient, this may take a while..."
+
+npx lint-staged
+
+result=$?
+if [ $result -ne 0 ]; then
+  echo "❌ Lint-staged checks failed. Commit aborted."
+  exit 1
+fi
+
+echo "✅ All checks passed. Proceeding with commit..."
